### ISSUE TITLE
Count Recovered people

### ISSUE THREAD

**Issue by nodenwwsfww** [Kamaropoulos/COVID19Py#15]
Hello, i noticed, that the count of recovered people is always equally, for the test.
        covid19 = COVID19Py.COVID19()
        latest = covid19.getLatest()
        print(
                        f"Confirmed case count: {latest['confirmed']}\n"
                         f"Death count: {latest['deaths']}\n"
                         f"Recovered count: {latest['recovered']}\n\n")
Result: 
1771514 (confirmed)
108503 (deaths)
0 (recovered)

**Comment by Kamaropoulos** [comment]
Unfortunately, the default/global data provider recently stopped providing recovery data.

https://github.com/ExpDev07/coronavirus-tracker-api#recovered-cases-showing-0
