### ISSUE TITLE
Get Daily Cases

### ISSUE THREAD

**Issue by Phoenix-64** [Kamaropoulos/COVID19Py#93]
It is annoying to manually calculate the daily cases is it possible to directly fetch them or calculate them in COVID19Py

Fetch the daily cases from the data source. JHU has them in GitHub as daily reports.
Or  a function could be added to COVID19Py that calculates the daily cases from the total reported cases upon this day

**Comment by lybkov** [comment]
The argument timelines=True allows you to access each day of the received data.
